import { Raleway } from "next/font/google";
import "./globals.css";
import { ShopAccessoryContextProvider } from "@/context/ShopAccessoryContext";

const raleway = Raleway({ subsets: ["latin"], weight: '400' });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={raleway.className}>
        <ShopAccessoryContextProvider>
          {children}
        </ShopAccessoryContextProvider>
        </body>
    </html>
  );
}
